### ISSUE TITLE
Bbcode parser - improperly handling url tags

### ISSUE THREAD

**Issue by adelikat** [adelikat/tasvideos#101]
Url tags are misbehaving:

This text (post id 464637):
In the recent Math Blaster submission somebody [url=http://tasvideos.org/forum/viewtopic.php?p=464588#464588]presented the suggestion[/url] that rather than define which [i]genres[/i] of games are acceptable and which aren't, instead it could be better to define the characteristics that a game needs to have, in order to be acceptable for TASing (and publication here).

Renders to:
<div class=postbody>In the recent Math Blaster submission somebody [url=<a href="http://tasvideos.org/forum/viewtopic.php">http://tasvideos.org/forum/viewtopic.php</a>?p=464588#464588]presented the suggestion[/url] that rather than define which <i>genres</i> of games are acceptable and which aren't, instead it could be better to define the characteristics that a game needs to have, in order to be acceptable for TASing (and publication here).

Notice the url tag itself is still in there

**Comment by nattthebear** [comment]
Very generally, the bbcode parser looks for opening tags that look like this:

`[name]`
`[name=options]`

Both _name_ and _options_ can be most characters, except for stuff like control characters, `[` and `]` themselves, and _name_ can't contain `/` as closing tags can contain that.  Also, neither is allowed to contain `=` since it's used to separate _name_ and _options_.  But urls can contain an `=` in _options_, which the parser is rejecting.

**Comment by nattthebear** [comment]
0e87b67cb22fb5a113f0528221306b6fb7e25a38
