### ISSUE TITLE
Tables with || in non header rows

### ISSUE THREAD

**Issue by adelikat** [adelikat/tasvideos#201]
https://tasvideos.quantium.tk/GameResources/Genesis/KidChameleon
http://tasvideos.org/GameResources/Genesis/KidChameleon.html

Not sure what we want to do about this one.

**Comment by vadosnaprimer** [comment]
Does it look harmful to support? If not, I'd have it.

**Comment by nattthebear** [comment]
```
||Character  ||Crawl||Walk  ||Run   ||Jump  ||Uphill||Downhill 
||Kid etc.    |1:0  | 2:0   | 3:128 | 2:160 | 1:0   | 3:0
||Maniaxe etc.|1:0  | 2:0   | 3:128 | 2:160 | 0     | 4:0
||Juggernaut  |--   | 1:128 | 3:0   | 2:128 | --    | -- 
||MicroMax    |--   | 1:0   | 2:0   | 1)    | 0:128 | 1:128 
||Skycutter   |--   | 2:0   | 4:0   | --    | --    | -- |
```

I'm not sure what to do here.  Even if I decline to parse `||` as `<thead><tr><th>` when already in a table and instead hit the next match which turns `|` into `<tbody><tr><td>`, because there's a second `|` right next to it, it will be parsed into an empty cell so everything will be off by one.

We don't have any idea how 99% of the wiki parsing is supposed to behave...

**Comment by nattthebear** [comment]
Did some more investigation.  The old parser is very very weird, but I know more about its behavior now and i think we can do this.  Key observations:
1.  There are no empty cells.  You must have at least one markdown character in any cell.  Additional `|` stacked next to each-other either change the cell type, are ignored, or cause the entire table parse to reject.
2.  The system never produces a <thead>, ever.

There's some weirdness for sure, and some edge cases I can't explain, but we should be able to get closer to the old behavior with something along the lines of

One or more `|` at start of line:  Start a table and tbody if we aren't in one.  Start a trow.  Start a th for 2 or more `|`, td otherwise.
One or more `|` in the middle of a line:  Close previous th or td.  Start a td if ther's only one `|`, th for two or more.

**Comment by nattthebear** [comment]
This works now, but the styling on the table is somewhat different.  `<th>` had more distinction in the old database, and when building tables with `<th>` along the top and `<th>` down the left side like the linked one, the end result is less than perfect.

**Comment by adelikat** [comment]
I styled the things better, closing
