### ISSUE TITLE
Investigate Syntax exceptions on existing pages

### ISSUE THREAD

**Issue by adelikat** [adelikat/tasvideos#32]
When importing existing wiki pages, many SyjntaxExceptions are thrown from the new wiki engine.
Investigate these to see if any of them can be mitigated during the import process

**Comment by nattthebear** [comment]
In some cases, the only way to get a real fix will be to have a human editor look at the page and redo the problem.  To that end, would it help to have a "Pages with Syntax Errors" listing?  That would be handy for investigating this.

**Comment by adelikat** [comment]
I like that idea

**Comment by nattthebear** [comment]
29050b1ac40de92c0787e36b7c0a295b5282 adds the page.  Next step will be to look at that page with real data and see what the patterns are.

**Comment by nattthebear** [comment]
About a dozen instances of unterminated `[` were seen.  In the old wiki, an unterminated `[` will just be treated as raw text.  The new wiki syntax errors on that.  We do have an escape sequence for `[`, so I'm not too worried and I think editors would rather get an error message rather than useful markup failing silently with no obvious reason.  Once the new site goes live, we can give a senior editor a punch list from Diagnostics/WikiSyntaxErrors and they can fix them in short order.

A handful of unmatched `%%TAB_END%%` were seen.  They all appeared to be errors in the source material.  I corrected a few of them on the live site, but left a few others that I could not easily resolve.  Once the new site goes live, we can give a senior editor a punch list from Diagnostics/WikiSyntaxErrors and they can fix them in short order.

TextFormattingRules/ListOfModules has an error due to import shenanigans.  This can be corrected by hand after the new site goes live.

And that's about it.  All told less than 20 things.  Not worth the effort of import fixups.
