### ISSUE TITLE
CycleCount and VBlank Count Parser Bugs

### ISSUE THREAD

**Issue by CasualPokePlayer** [adelikat/tasvideos#320]
1. You can hack in some stupid times in by editing cycle count for Gambatte/SubGBHawk submissions, notably you can slap a negative cycle count in too. Same with VBlank count for SubNESHawk submissions.

2. Apparently putting in 2^63 - 1 cycles (iirc?) in gives a time of 5090331:19:02:06.7500032 which seems to indicate rounding broke with that time?

3. Infinity fps is possible (ok maybe not so much a "bug" but meme anyways, probably should throw some error anyways)

4. NaN fps is possible (crashes site if it tries to divide by that, e.g. submissions tables is borked)

**Comment by adelikat** [comment]
Broke the author edit into a separate ticket here: https://github.com/adelikat/tasvideos/issues/321
So that this is a collection of submission parser issues

**Comment by adelikat** [comment]
I think I fixed all of the crashes related to this.  It now ignores negative numbers.  It can't really filter to "reasonable" values since it is hard to know what those are.  I fixed some divide by 0 issues so it can't crash the front page now.  Unless it can break, I'm okay with garbage in = garbage out, and we have some silly things like Infinitely for cycle count.  These issues are easily fixed by a judge (through fixing or rejection), so I don't see it as a big deal
