### ISSUE TITLE
[Subs-[expr:UserGetId]up|your own] doesn't work

### ISSUE THREAD

**Issue by vadosnaprimer** [adelikat/tasvideos#333]
`List [Subs-[expr:UserGetId]up|your own]` doesn't generate a link to my own submissions
https://tasvideos.mistflux.net/Subs-List

**Comment by adelikat** [comment]
@nattthebear : Correct me if I'm wrong, but we do not support expr in the new parser? And I do not believe we desire to do so.

We do not need this wiki markup since submission pages have their own links (and are not wiki).  If you want to show your own submissions, you can just put your username/id into the markup.  Is there a place where we need it to be a dynamic link based on user? If so, I can easily throw together a module that can accomplish this

**Comment by nattthebear** [comment]
This is one of the things in the old site that was very problematic because it's implemented as a separate parsing layer. where `[expr:` in the raw text was found, replaced, and then the result of that was sent to the next parser.  So it supported (in a very limited way) the module in the params of another module syntax you see here.

We support a few expr modules, namely `expr:UserGetWikiName` `expr:WikiGetCurrentEditLink`, but only through normal module syntax.  Text inside a `[` ... `]` is never sent to another layer of module parsing.

@adelikat You are correct in that this was something I pushed back on a while ago.  The syntax is awkward and you can do all sorts of screwy stuff with it.  I think your approach of creating a new module to handle this specific use case, if it's needed, is appropriate.

**Comment by adelikat** [comment]
We do not want to support this particular expr module going forward.  The only usage that was important was the "list your own submissions" link which is now no longer in a wiki module.  I would be happy to support a dedicated module for this feature in the future if deemed useful.

But going forward we will not support exr:UserGetId.  Also note, that even if we did, the id would be wrong since we have merged user tables and everyone's id is now the forum id, not the site id that it uses.
