### ISSUE TITLE
When cataloging the submission, a weird list of options is available for system framerate

### ISSUE THREAD

**Issue by vadosnaprimer** [adelikat/tasvideos#338]
https://i.imgur.com/PG2rJlH.png
https://i.imgur.com/6jT6DRk.png
and nothing for ROM.

**Comment by adelikat** [comment]
Nothing for ROM because there are no ROMs, we will have to build up a database of those.  This is expected.

All of those framerates are ones that are actually used in historical movies.  It's a mess because our old systems are a mess.  You don't feel the pain on the old site since it is just a time, many of these are not known to be a different framerate, but if you do the math, it's all over the place.

I believe you have to see all of them too.  While you should not use any that say (obsolete), you need to be able to set an old publication to that value, if for some reason it was set to the wrong value by mistake.
