### ISSUE TITLE
Judge should not be able to judge their own submission

### ISSUE THREAD

**Issue by vadosnaprimer** [adelikat/tasvideos#343]
I was able to accept my own submission, even before its timeout ended (1 hour). Shouldn't be able to do that.
https://tasvideos.mistflux.net/7202S

**Comment by adelikat** [comment]
Judges can not accept their own submissions.  However, you are a senior judge which grants you the OverrideSubmissionStatus permissions, that allows both judging before the timeout period, and setting any status of any submission (including one's own).  This is by design, we can debate if a Senior judge should have this, but I think the point of the role is to afford this level of trust to the user.

**Comment by vadosnaprimer** [comment]
Oh. I don't have good reasons to disallow this, because I don't feel this urge very often to just accept my shitpost submissions.
