### ISSUE TITLE
Publication Discuss button missing on movie lists

### ISSUE THREAD

**Issue by bigbass1997** [adelikat/tasvideos#410]
When viewing an individual publication, you will see a "Discuss" button that takes you to the respective forum thread. However, when you find any pub on any movie list (such as https://tasvideos.mistflux.net/Movies-NES-FDS), that button doesn't appear. 

This means there's no way to hop directly from the list to any given pub's discussion thread.

**Comment by adelikat** [comment]
The problem is that the single publication page does this one off logic, after querying the publication data:
var pageName = LinkConstants.SubmissionWikiPage + Publication.SubmissionId;
Publication.TopicId = (await _db.ForumTopics
  .SingleOrDefaultAsync(t => t.PageName == pageName))
  ?.Id ?? 0;

The list page would have to do this for every publication, being way too slow. 

The fix is to work that logic into the query (specifically the auto-mapper logic) in a way that it can be queried in one database trip, then remove the one-off code
