### ISSUE TITLE
Broken links to the first post in submission discussion threads

### ISSUE THREAD

**Issue by SandTAS** [adelikat/tasvideos#458]
The old site had TASVideoAgent open a submission discussion thread by making the first post in the thread. The rewrite puts the submission text in a separate area, above the actual discussion posts.
* http://tasvideos.org/forum/viewtopic.php?t=22805
* https://tasvideos.mistflux.net/Forum/Topics/22805

The rewrite's way is better, IMO, but any third-party links to the first *post* (not the thread itself) are currently broken; e.g.,
* http://tasvideos.org/forum/viewtopic.php?p=508223#508223 (works)
* https://tasvideos.mistflux.net/Forum/Posts/508223#508223 (redirects to /Forum/NotFound#508223)

It's a small thing, but one solution would be to redirect such links to the first page of the discussion thread.

**Comment by adelikat** [comment]
It isn't very feasible to to do a redirect as you suggest, there are thousands of routes, and no programmatic way to determine if a post used to be the first post of a given submission.  Due to how much better the new way is, I'm okay with the possibility of links being broken "out in the wild" like this.  My guess is that these are rare anyway and that the submission link would be used
